USE [master]
GO
/****** Object:  Database [ClientsBase]    Script Date: 30.07.2023 17:56:11 ******/
CREATE DATABASE [ClientsBase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ClientsBase', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\ClientsBase.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ClientsBase_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\ClientsBase_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [ClientsBase] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ClientsBase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ClientsBase] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ClientsBase] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ClientsBase] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ClientsBase] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ClientsBase] SET ARITHABORT OFF 
GO
ALTER DATABASE [ClientsBase] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ClientsBase] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ClientsBase] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ClientsBase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ClientsBase] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ClientsBase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ClientsBase] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ClientsBase] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ClientsBase] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ClientsBase] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ClientsBase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ClientsBase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ClientsBase] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ClientsBase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ClientsBase] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ClientsBase] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ClientsBase] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ClientsBase] SET RECOVERY FULL 
GO
ALTER DATABASE [ClientsBase] SET  MULTI_USER 
GO
ALTER DATABASE [ClientsBase] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ClientsBase] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ClientsBase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ClientsBase] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ClientsBase] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ClientsBase] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'ClientsBase', N'ON'
GO
ALTER DATABASE [ClientsBase] SET QUERY_STORE = ON
GO
ALTER DATABASE [ClientsBase] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [ClientsBase]
GO
/****** Object:  Table [dbo].[Clients]    Script Date: 30.07.2023 17:56:11 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Clients](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CitizenID] [char](9) NOT NULL,
	[PhoneNumber] [nvarchar](50) NOT NULL,
	[FirstName] [nvarchar](100) NULL,
	[LastName] [nvarchar](100) NULL,
	[BitrthDate] [date] NULL,
	[Notes] [nchar](10) NULL,
 CONSTRAINT [PK_Clients] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [IX_Clients] UNIQUE NONCLUSTERED 
(
	[CitizenID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [ClientsBase] SET  READ_WRITE 
GO
